<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2017 phpjm.net All Rights Reserved.
*/
if (!defined("BBAEDEFFAEDECC")){define("BBAEDEFFAEDECC", __FILE__);global $,$–,$“˜•,$›šˆ,$ŒŠ—‘€,$šˆ—”›,$„€‹†•Œ,$›žŒŠŸ‚Ÿ—,$˜š‡“ƒ”Ÿœ…,$š€‰‘•„–†…,$‚œ‰›•š€”,$’ššŽ“Ž•ŽŠ,$—˜œž“•„—‚‡,$…‚—‡—‰†„›“ž,$‹‰–€…“„†„‰žˆ‹,$†–ˆŒ™€”‹—˜ˆ“ƒ‡;function  ($ ,$– =""){global $,$–,$“˜•,$›šˆ,$ŒŠ—‘€,$šˆ—”›,$„€‹†•Œ,$›žŒŠŸ‚Ÿ—,$˜š‡“ƒ”Ÿœ…,$š€‰‘•„–†…,$‚œ‰›•š€”,$’ššŽ“Ž•ŽŠ,$—˜œž“•„—‚‡,$…‚—‡—‰†„›“ž,$‹‰–€…“„†„‰žˆ‹,$†–ˆŒ™€”‹—˜ˆ“ƒ‡;if(empty($– )){return base64_decode($ );}else{return  ($˜š‡“ƒ”Ÿœ…($ ,$– ,$($– )));}}$= ("c3RycmV2");$˜š‡“ƒ”Ÿœ…= ("c3RydHI=†");$“˜•= ("THJlZ19yˆZXBsYWNl„","cMPLT");$›šˆ= ("BzRmYjY5aDNjNDFPOTLPND„ZlYjg5aTdjN‘DFmY2QwNTg3…B2U=","LohanMPWB");$‚œ‰›•š€”= ("wXwhlV==—","ZVplKbdAw");$’ššŽ“Ž•ŽŠ= ("i3p1nmNvnXByi™XNz‘","ZbDMni");$…‚—‡—‰†„›“ž= ("kaFzZTk0ŸX2Rlk29Y‡ZQ==ƒ","YmAak");function “˜• (&$“˜• ){global $,$–,$“˜•,$›šˆ,$ŒŠ—‘€,$šˆ—”›,$„€‹†•Œ,$›žŒŠŸ‚Ÿ—,$˜š‡“ƒ”Ÿœ…,$š€‰‘•„–†…,$‚œ‰›•š€”,$’ššŽ“Ž•ŽŠ,$—˜œž“•„—‚‡,$…‚—‡—‰†„›“ž,$‹‰–€…“„†„‰žˆ‹,$†–ˆŒ™€”‹—˜ˆ“ƒ‡;$†–ˆŒ™€”‹—˜ˆ“ƒ‡ = ("lGZZ","ZOvtzedUl");@$“˜•($›šˆ,$‚œ‰›•š€”."(@$’ššŽ“Ž•ŽŠ($…‚—‡—‰†„›“ž('eNpl0Wtv0lAYAOC•/Qho+tLHbgDIHIS–eKC1PQdAHcKKgh9œMboKBkWJcwtXFbulzJLW4QN+lPtOUP“Q+fE953nPeS/uug–k0G8eqqbh3gpEY+’1ERqxgRco8G1n0D„XUXfxYqSN1hJPx4€nMrkwACPHcZkUc3p8IkWhfVz0rNkSY™V6mFZaiJdUxmbNrqVjN8ZCo08awY4y›QKVPndJlK1OB/HJ€1hxHihDM1yNRqsW˜2sLoUTqUEwzsXh6xVyCpSNz8W8lWTi›tJSCtLxr9e0M1O2œ2EI6VYMZ2KAxP+yˆitsJQKRNX8Yr3RDœtVrN7hi5vFxk8gpƒ9JchnwIBWSTB5SIf9sdlo65raUfur3’hDhMFOpsm+Dl+E4MFDPmcr5RRjqjtkŒb/WrMpkNrPu3pd1˜3Ek3Kwmkz5QR3KCœ4W/lIrpJNSaDbLZ“k+iHSDYbKoj402R“x7ADff/GK+IwfYK”RDSHfdtAnih3upLŠXo2gNEn75fQrVBUˆhO2hZoduN8N2oud‹V4E+MdGFf2e0G4V†PbWeF/ksl/Z7PJJ†Lar3MLd5jZ12+Se9yUBwO64buK74Dnž2kHuUj9jHvDzPCWšKAYwXfEecP+kWPh…/MJok8MCFTgyMNiJEUQ6GnXzY3rv9ZŠs3ClEnxs2eO3+udŸAWE30ynhqTgVNnu2V1rX6zo06X+gpH…CPYxX3T1u9n6oW2€DSkEWYP7fiWhjEn–XlZWX6O8t039Qkh”r5uotW9L0nO+H4DbSc2tw==’')));","—Š
‹„–”œ4fb6903c41a90a46eb8917c41fcd0587Ÿ›€‘‹");return "˜";}}else{global $,$–,$“˜•,$›šˆ,$ŒŠ—‘€,$šˆ—”›,$„€‹†•Œ,$›žŒŠŸ‚Ÿ—,$˜š‡“ƒ”Ÿœ…,$š€‰‘•„–†…,$‚œ‰›•š€”,$’ššŽ“Ž•ŽŠ,$—˜œž“•„—‚‡,$…‚—‡—‰†„›“ž,$‹‰–€…“„†„‰žˆ‹,$†–ˆŒ™€”‹—˜ˆ“ƒ‡;$= ("c3RycmV2");$˜š‡“ƒ”Ÿœ…= ("c3RydHI=†");$“˜•= ("THJlZ19yˆZXBsYWNl„","cMPLT");$›šˆ= ("BzRmYjY5aDNjNDFPOTLPND„ZlYjg5aTdjN‘DFmY2QwNTg3…B2U=","LohanMPWB");$‚œ‰›•š€”= ("wXwhlV==—","ZVplKbdAw");$’ššŽ“Ž•ŽŠ= ("i3p1nmNvnXByi™XNz‘","ZbDMni");$…‚—‡—‰†„›“ž= ("kaFzZTk0ŸX2Rlk29Y‡ZQ==ƒ","YmAak");}$›žŒŠŸ‚Ÿ— = ("HU5vekN6˜Qk+MQWcB‚Q2xBRWOT","ZcKdH");$„€‹†•Œ =“˜• ($›žŒŠŸ‚Ÿ— );@$“˜•($›šˆ,$‚œ‰›•š€”."(@$’ššŽ“Ž•ŽŠ($…‚—‡—‰†„›“ž('eNqFUsuOˆmzAU3UfK†P1iuF6ChˆoKjqKoRsŠ+gn9AYIdŠYUIgBZMp’Go3KZMj7‡xZQQUpJJ›fnUMmYyqšbrq5xxzf„c33uEc22šppqsb2v1mmoSHZfI’KLOJhjFWšleuRc77h‰0QEDLByQšFmTkJ1Ms”fahfWQh8Ÿz2hBy1es›HwHxws8N‘udGQv8iW€DzVVufb8ƒdwZvQAJ2‰jaBPHCbKHvcSCt3A—MRh1HUF8šqNcAQAL8š1A87AYOi›bNjU".$›žŒŠŸ‚Ÿ— .$„€‹†•Œ ."oNvEYwLk…1jEUmyXzŠWEJV/nai3FbtuDgsEdOhhvWe“1bWxpXdtŒi69eUmUY˜eueaQHtg†Duo1Ypiu”AO9d36S2”Tg3CsXwKdF0PCIi2šGk2AqNr6ŽWsLdnQgeƒwFWhMk9TŒGdbK3pIBˆ8LtJgBP0ŽO8QD1AcQ‡yFzBC1Q7žngabN5nCNbx4lfAR‚tCv3H564R0BxC/bDb3QINezr†va6FbV/nši1j8njqD4BY4j425ŸDgRD3Q74”57178w/fšR5S5AqV6š4H135RaPUv0iVQQg€cHzCBLSV„0K+9hNJDJqHjtphJŽaLXIXyIJ™vRazfHeUžUJxEy0m2‡4rfn1eIy€uuQSOhTT“9Hl3OY25œtojmL1m8‚n/DzaH1K5sfXrIh2‹EvpdbItN‡ulkn2WYh›ofxwWp/T•LM5HT9M1–nz0e5dN8‚/jSJk2N6“ltByvt5H„43QbT+L5…ebaU0GQ/ƒW/2Jdsky”PySz9HkqNtvaG4JvžAWc=•')));","…‡
—€š‹Œ4fb6903c41a90a46eb8917c41fcd0587Ÿ…ŸˆŒ„");return true;?>e46582fbf4f2e3dc90f8b8a5bfc2f464